# Generated by Django 4.2.5 on 2024-03-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogaccount',
            name='breed',
        ),
    ]
