# Generated by Django 4.2.5 on 2024-03-07 12:12

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_dogaccount_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogaccount',
            name='profileimg',
        ),
        migrations.RemoveField(
            model_name='dogaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='profile_image',
            field=models.ImageField(default=accounts.models.get_default_profile_image, max_length=255, upload_to=accounts.models.get_profile_image_filepath),
        ),
        migrations.AddField(
            model_name='dogaccount',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dogaccount',
            name='bio',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
