# Generated by Django 4.2.5 on 2024-03-07 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_dogaccount_profileimg_remove_dogaccount_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogaccount',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
    ]
