# Generated by Django 4.2.5 on 2024-03-11 11:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dogaccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogaccount',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.get_default_profile_image, max_length=255, upload_to=accounts.models.get_profile_image_filepath),
        ),
    ]
